# University names and their short forms
universityNames = {
    'Ahsanullah University of Science and Technology': 'AUST',
    'BRAC University': 'BRACU',
    'Shahjalal University of Science & Technology': 'SUST',
    'Bangladesh University of Engineering & Technology': 'BUET',
    'Chittagong University of Engineering & Technology': 'CUET',
    'Khulna University of Engineering & Technology': 'KUET',
    'Rajshahi University of Engineering and Technology': 'RUET',
    'Dhaka University of Engineering and Technology': 'DUET',
    'Islamic University of Technology': 'IUT',
    'Jahangirnagar University': 'JU',
    'University of Dhaka': 'DU',
    'Comilla University': 'CoU',
    'University of Chittagong': 'CU',
    'University of Rajshahi': 'RU',
    'University of Khulna': 'KU',
    'Jagannath University': 'JnU',
    'Bangladesh University of Professionals': 'BUP',
    'Bangladesh Agricultural University': 'BAU',
    'Sylhet International University': 'SIU',
    'Jessore University of Science & Technology': 'JUST',
    'Mawlana Bhashani Science & Technology University': 'MBSTU',
    'University of Barishal': 'BU',
    'North South University': 'NSU',
    'International Islamic University Chittagong': 'IIUC',
    'East West University': 'EWU',
    'University of Rajshahi': 'RU',
    'Metropolitan University': 'MU',
    'North East University Bangladesh': 'NEUB',
    'Military Institute of Science & Technology': 'MIST',
    'Islamic University, Bangladesh': 'IU',
    'Patuakhali Science And Technology University': 'PSTU',
    'Bangladesh University of Business & Technology': 'BUBT',
    'University of Information Technology & Sciences': 'UITS',
    'Daffodil International University': 'DIU',
    'United International University': 'UIU',
    'University of Asia Pacific': 'UAP',
    'Green University of Bangladesh': 'GUB',
    'Sylhet Engineering College': 'SEC',
    'Noakhali Science & Technology University': 'NSTU',
    'Independent University, Bangladesh': 'IUB',
    'Dhaka University of Engineering & Technology': 'DUET',
    'East Delta University': 'EDU',
    'American International University-Bangladesh': 'AIUB',
    'National University' : 'NU',
    'Leading University': 'LU',
    'Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj': 'BSMRUK',
    'Varendra University': 'VU',
    'DHAKA CITY COLLEGE': 'DCC',
    'Begum Rokeya University, Rangpur': 'BRUR',
    'International University of Business Agriculture & Technology': 'IUBAT',
    'Sheikh Hasina University': 'SHU',
    'Hajee Mohammad Danesh Science & Technology University': 'HSTU',
    'BAIUST, Comilla': 'BAIUST',
    'Mymensingh Engineering College': 'MEC',
    'Shanto-Mariam University of Creative Technology': 'SMUCT',
    'Southeast University': 'SEU',
    'National Institute of Textile Engineering and Research - NITER': 'NITER',
    'Chittagong Independent University': 'CIU',
}